### PR TITLE
Add Soccer IPM Module 

### PR DESCRIPTION
**Pull request by Flova**
This PR includes mainly some hacky code used to get the IPM up and running for the German Open tournament.
I will convert this PR into a proper module which implements a standard IPM for converting the `soccer_vision_2d_msgs` into `soccer_vision_3d_msgs` by assuming a field plane and a base_footprint.

TODOs:

- [x] use `base_footprint` not available while testing
- [x] use the `soccer_vision_3d_msgs` for publishing Cartesian coordinates
- [ ] improve documentation
- [ ] improve formatting
- [ ] add unit tests
- [ ] add proper documentation
- [ ] support rotated bounding boxes

### CODE REVIEW

**Comment by ijnek** [comment]
I don't know what your intention is with this PR after RoboCup, but I'd definitely want the soccer-related stuff to be in a separate repo (and not in IPM). Perhaps I can set up a new repo called ``soccer_ipm``?

**Comment by jaagut** [comment]
> I don't know what your intention is with this PR after RoboCup, but I'd definitely want the soccer-related stuff to be in a separate repo (and not in IPM). Perhaps I can set up a new repo called ``soccer_ipm``?

Yes, the idea is to merge this into a upstream repo. ``soccer_ipm`` is a good name, I belive. We just used this branch during the robocup

**Comment by ijnek** [comment]
Great, I've set up the repo and added you both as a maintainer: https://github.com/ros-sports/soccer_ipm

**Comment by Flova** [comment]
The soccer ipm is now on https://github.com/ros-sports/soccer_ipm this pr is still used to request changes on the ipm library for the soccer ipm.

**Review by ijnek — APPROVED** [review]

**Pull request merged**
